// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtacloomdmbchkaxpmsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0YWNsb29tZG1iY2hrYXhwbXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTA0NzQsImV4cCI6MjA2ODUyNjQ3NH0.8KuFGJccJ_iuiXs_x5SMe8FaPdKJHCRV1Qtny0dXs-I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});